### ISSUE TITLE
aporia

### ISSUE THREAD

**Issue by ezra1** [nim-lang/gtk2#12] opened 2015-01-31 22:22 UTC
trying to get aporia up and running.  Its an issue specific to openbsd and iconv_open (openbsd uses libiconv_open, libconv*
aporia compiles, but when trying to open it I get cannot import iconv_open
I'm trying to work around it and found glib2.nim is where iconv dynlib resides, just not sure how to change it to get it work

**Comment by winksaville** [comment] 2015-03-01 05:52
I ran into the same problem, any solution?

**Comment by ezra1** [comment] 2015-03-02 17:50
never figured it out, moved on

**Comment by aboisvert** [comment] 2015-03-27 15:29
FYI, this is a duplicate of https://github.com/nim-lang/gtk2/issues/12

**Comment by dom96** [comment] 2015-03-27 22:32
This also doesn't seem to have anything to do with gtk.

**Closed by dom96** 2015-03-27 22:32 UTC

**Comment by ringabout** [comment] 2021-04-27 07:14
well it is still not fixed
